version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sysflow-postgres
    restart: always
    environment:
      POSTGRES_USER: sysflow_user
      POSTGRES_PASSWORD: sysflow_password
      POSTGRES_DB: sysflow_dev
    ports:
      - "5433:5432"
    volumes:
      - sysflow_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sysflow-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - sysflow_redis_data:/data

volumes:
  sysflow_postgres_data:  
  sysflow_redis_data: